DROP TABLE IF EXISTS vendors;
CREATE TABLE vendors (
  id INTEGER PRIMARY KEY ASC, -- Primary key vendor id, autogenerated
  first_name VARCHAR(80),     -- The first name of the vendor
  last_name VARCHAR(80),      -- The last name of the vendor
  phone_number VARCHAR(80)    -- The phone number of the vendor
);

DROP TABLE IF EXISTS vendor_numbers;
CREATE TABLE vendor_numbers (
  id INTEGER PRIMARY KEY ASC,  -- Primary key purchase id, autogenerated
  vendor_number INTEGER,       -- The item number
  vendor_id INTEGER            -- The vendor id (foreign key)
);

DROP TABLE IF EXISTS purchases;
CREATE TABLE purchases (
  id INTEGER PRIMARY KEY ASC, -- Primary key purchase id, autogenerated
  item_number INTEGER,        -- The item number
  item_price DOUBLE,          -- The item price
  vendor_number INTEGER       -- The vendor number
);
